name: blue
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  oktoast: ^3.0.0
  image: ^3.0.2
  esc_pos_bluetooth:
    path: ../../
  esc_pos_utils: ^1.1.0
  # esc_pos_utils:
  # path: ../../../esc_pos_utils
  charset_converter: ^2.0.0
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.2
  image_picker: ^0.8.4+3
  shared_preferences: ^2.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  async: ^2.8.1
  flutter_lints: ^1.0.0
  url_launcher: ^6.0.12
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo216.png
    - assets/logo222.png
    - assets/rabbit_black.jpg
